services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ops_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  pg_data: