from src.services.ordering_service.autonomy_checks import autonomy_checks
from src.services.ordering_service.horizon import horizon_aggregate, protection_horizon
from src.services.ordering_service.proposals import generate_proposals
