"""edit autonomy tables

Revision ID: 049740325dd1
Revises: 2c4df6340d0a
Create Date: 2026-08-07 14:06:38.925293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049740325dd1'
down_revision: Union[str, Sequence[str], None] = '2c4df6340d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spend_ledger', sa.Column('business_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spend_ledger', 'business_date')
    # ### end Alembic commands ###
