"""add sales types to table

Revision ID: 1390ec583a96
Revises: c5378519df63
Create Date: 2026-07-28 08:53:23.488712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1390ec583a96'
down_revision: Union[str, Sequence[str], None] = 'c5378519df63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_transactions', sa.Column('transaction_type', sa.Text(), server_default='sale', nullable=False))
    op.add_column('sale_transactions', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.create_check_constraint(
        "sale_transactions_transaction_type_check",
        "sale_transactions",
        "transaction_type IN ('sale', 'void', 'refund')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sale_transactions_transaction_type_check", "sale_transactions")
    op.drop_column('sale_transactions', 'discount_amount')
    op.drop_column('sale_transactions', 'transaction_type')
    # ### end Alembic commands ###
