"""edit forecast tables

Revision ID: 21013894b789
Revises: c4ec1b8a653d
Create Date: 2026-07-30 07:46:48.915836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21013894b789'
down_revision: Union[str, Sequence[str], None] = 'c4ec1b8a653d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_metrics', sa.Column('forecast_date', sa.Date(), nullable=False))
    op.drop_constraint(op.f('forecast_metrics_tenant_series_target_model_key'), 'forecast_metrics', type_='unique')
    op.create_unique_constraint('forecast_metrics_tenant_series_target_model_fcdate_key', 'forecast_metrics', ['tenant_id', 'series', 'target_date', 'model_version', 'forecast_date'])
    op.add_column('forecasts', sa.Column('forecast_date', sa.Date(), nullable=False))
    op.drop_constraint(op.f('forecasts_tenant_series_target_model_key'), 'forecasts', type_='unique')
    op.create_unique_constraint('forecasts_tenant_series_target_model_fcdate_key', 'forecasts', ['tenant_id', 'series', 'target_date', 'model_version', 'forecast_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forecasts_tenant_series_target_model_fcdate_key', 'forecasts', type_='unique')
    op.create_unique_constraint(op.f('forecasts_tenant_series_target_model_key'), 'forecasts', ['tenant_id', 'series', 'target_date', 'model_version'], postgresql_nulls_not_distinct=False)
    op.drop_column('forecasts', 'forecast_date')
    op.drop_constraint('forecast_metrics_tenant_series_target_model_fcdate_key', 'forecast_metrics', type_='unique')
    op.create_unique_constraint(op.f('forecast_metrics_tenant_series_target_model_key'), 'forecast_metrics', ['tenant_id', 'series', 'target_date', 'model_version'], postgresql_nulls_not_distinct=False)
    op.drop_column('forecast_metrics', 'forecast_date')
    # ### end Alembic commands ###
