"""add weather model

Revision ID: 29480ee4c2a7
Revises: 35a0a9f8796d
Create Date: 2026-07-22 13:20:11.085552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29480ee4c2a7'
down_revision: Union[str, Sequence[str], None] = '35a0a9f8796d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('max_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('precipitation_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'observation_date', 'source', name='weather_observations_tenant_date_source_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
