"""add coordinates to Tenants

Revision ID: 35a0a9f8796d
Revises: 4e245e2f500c
Create Date: 2026-07-22 13:16:21.870525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a0a9f8796d'
down_revision: Union[str, Sequence[str], None] = '4e245e2f500c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('tenants', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'latitude')
    op.drop_column('tenants', 'longitude')
    # ### end Alembic commands ###
