"""fix model tables

Revision ID: 379537ded373
Revises: bb02a598b007
Create Date: 2026-08-09 13:05:15.059375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379537ded373'
down_revision: Union[str, Sequence[str], None] = 'bb02a598b007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('challenger_version', sa.Text(), nullable=False))
    op.add_column('backtest_results', sa.Column('champion_version', sa.Text(), nullable=False))
    op.add_column('backtest_results', sa.Column('passed', sa.Boolean(), nullable=False))
    op.drop_column('backtest_results', 'series')
    op.drop_column('backtest_results', 'model_version')
    op.drop_constraint(op.f('model_registry_tenant_series_key'), 'model_registry', type_='unique')
    op.create_unique_constraint('model_registry_tenant_key', 'model_registry', ['tenant_id'])
    op.drop_column('model_registry', 'series')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('series', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('model_registry_tenant_key', 'model_registry', type_='unique')
    op.create_unique_constraint(op.f('model_registry_tenant_series_key'), 'model_registry', ['tenant_id', 'series'], postgresql_nulls_not_distinct=False)
    op.add_column('backtest_results', sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('backtest_results', sa.Column('series', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('backtest_results', 'passed')
    op.drop_column('backtest_results', 'champion_version')
    op.drop_column('backtest_results', 'challenger_version')
    # ### end Alembic commands ###
