"""add health check table

Revision ID: 42cd4208fc98
Revises: a22611ff87f7
Create Date: 2026-07-27 16:41:18.593403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42cd4208fc98'
down_revision: Union[str, Sequence[str], None] = 'a22611ff87f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consumer_name', sa.Text(), nullable=False),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_name', name='heartbeats_consumer_name_key')
    )
    op.add_column('purchase_orders', sa.Column('created_by', sa.Text(), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'created_by')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
