"""fix categories

Revision ID: 52490ed66d5b
Revises: 7a413e88d0af
Create Date: 2026-08-08 08:29:06.015829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52490ed66d5b'
down_revision: Union[str, Sequence[str], None] = '7a413e88d0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='categories_tenant_id_item_name_key')
    )
    op.add_column('inventory_items', sa.Column('category_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'inventory_items', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('inventory_items', 'category')
    op.add_column('shrinkage_rates', sa.Column('category_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('shrinkage_rates_tenant_id_category_key'), 'shrinkage_rates', type_='unique')
    op.create_unique_constraint('shrinkage_rates_tenant_id_category_id_key', 'shrinkage_rates', ['tenant_id', 'category_id'])
    op.create_foreign_key(None, 'shrinkage_rates', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('shrinkage_rates', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shrinkage_rates', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shrinkage_rates', type_='foreignkey')
    op.drop_constraint('shrinkage_rates_tenant_id_category_id_key', 'shrinkage_rates', type_='unique')
    op.create_unique_constraint(op.f('shrinkage_rates_tenant_id_category_key'), 'shrinkage_rates', ['tenant_id', 'category'], postgresql_nulls_not_distinct=False)
    op.drop_column('shrinkage_rates', 'category_id')
    op.add_column('inventory_items', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
