"""add forecast tables

Revision ID: 58486cce5b7d
Revises: 1390ec583a96
Create Date: 2026-07-28 13:59:42.753057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58486cce5b7d'
down_revision: Union[str, Sequence[str], None] = '1390ec583a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_actuals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('series', sa.Text(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'series', 'actual_date', name='daily_actuals_tenant_series_date_key')
    )
    op.create_table('forecast_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('series', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('mae', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wape', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bias', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('skill', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('coverage', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'series', 'target_date', 'model_version', name='forecast_metrics_tenant_series_target_model_key')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('series', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('point_estimate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantile_grid', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'series', 'target_date', 'model_version', name='forecasts_tenant_series_target_model_key')
    )
    op.add_column('tenants', sa.Column('owner_email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'owner_email')
    op.drop_table('forecasts')
    op.drop_table('forecast_metrics')
    op.drop_table('daily_actuals')
    # ### end Alembic commands ###
