"""remove invoice tables

Revision ID: 63a719abb6d6
Revises: 428e59cd652e
Create Date: 2026-08-17 10:38:35.268239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a719abb6d6'
down_revision: Union[str, Sequence[str], None] = '428e59cd652e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_lines')
    op.drop_table('invoices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('supplier_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('invoice_lines_inventory_item_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('invoice_lines_invoice_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_item_id'], ['supplier_items.id'], name=op.f('invoice_lines_supplier_item_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('invoice_lines_tenant_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoice_lines_pkey'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vendor_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('supplier_id IS NOT NULL OR vendor_name IS NOT NULL', name=op.f('invoices_supplier_or_vendor_check')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('invoices_supplier_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('invoices_tenant_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    # ### end Alembic commands ###
