"""add learning loop tables

Revision ID: 6e4b6e133eb2
Revises: ed06d5dde140
Create Date: 2026-08-08 14:44:55.072346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e4b6e133eb2'
down_revision: Union[str, Sequence[str], None] = 'ed06d5dde140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_factors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('clamp_low', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('clamp_high', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('half_life', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_clamps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', 'scope_key', name='correction_factors_tenant_id_kind_scope_key_key')
    )
    op.create_table('factor_histories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('correction_factor_id', sa.UUID(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('new_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('observation', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('clamped', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['correction_factor_id'], ['correction_factors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factor_histories')
    op.drop_table('correction_factors')
    # ### end Alembic commands ###
