"""add edits to POEvent table

Revision ID: 7a413e88d0af
Revises: 049740325dd1
Create Date: 2026-08-07 16:46:44.438615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a413e88d0af'
down_revision: Union[str, Sequence[str], None] = '049740325dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_events', sa.Column('edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('po_events', 'edits')
    # ### end Alembic commands ###
