"""update inv transaction types

Revision ID: 8d0466dda32d
Revises: 93665213a2c9
Create Date: 2026-08-18 14:09:59.554070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0466dda32d'
down_revision: Union[str, Sequence[str], None] = '93665213a2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factor_histories', sa.Column('business_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factor_histories', 'business_date')
    # ### end Alembic commands ###
