"""update inventory item for suppliers

Revision ID: 9d562423f1c1
Revises: bb7acce87fcb
Create Date: 2026-07-25 09:36:39.922350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d562423f1c1'
down_revision: Union[str, Sequence[str], None] = 'bb7acce87fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('target_quantity', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('inventory_items', 'supplier')
    op.drop_column('inventory_items', 'reorder_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('reorder_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('inventory_items', sa.Column('supplier', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('inventory_items', 'target_quantity')
    # ### end Alembic commands ###
