"""add address to tenant for search

Revision ID: 9d9a095d8f95
Revises: adc58e50c8a3
Create Date: 2026-07-22 16:00:31.292203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9a095d8f95'
down_revision: Union[str, Sequence[str], None] = 'adc58e50c8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('address', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'address')
    # ### end Alembic commands ###
