"""update share vectors table

Revision ID: b41c245aab32
Revises: 244dee9aeb43
Create Date: 2026-07-30 14:28:33.101912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41c245aab32'
down_revision: Union[str, Sequence[str], None] = '244dee9aeb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('share_vectors_tenant_item_dow_key'), 'share_vectors', type_='unique')
    op.create_unique_constraint('share_vectors_tenant_item_dow_date_key', 'share_vectors', ['tenant_id', 'inventory_item_id', 'day_of_week', 'as_of_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('share_vectors_tenant_item_dow_date_key', 'share_vectors', type_='unique')
    op.create_unique_constraint(op.f('share_vectors_tenant_item_dow_key'), 'share_vectors', ['tenant_id', 'inventory_item_id', 'day_of_week'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
