"""edit forecast tables

Revision ID: c4ec1b8a653d
Revises: 58486cce5b7d
Create Date: 2026-07-29 08:58:24.496488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ec1b8a653d'
down_revision: Union[str, Sequence[str], None] = '58486cce5b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_metrics', 'wape')
    op.drop_column('forecast_metrics', 'skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_metrics', sa.Column('skill', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('forecast_metrics', sa.Column('wape', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
