OPENING_HOUR = 10
OPENING_MINUTE = 0
CLOSING_HOUR = 6
CLOSING_MINUTE = 0

SCHEDULE_GEN_DAY_OF_WEEK = "wed"
SCHEDULE_GEN_HOUR = 9
SCHEDULE_GEN_MINUTE = 0

CLAIM_INTERVAL_SECONDS = 30

INVENTORY_POLL_INTERVAL = 3600 * 3